repos:
  - repo: local
    hooks:
      - id: update-readme
        name: update-readme
        files: ^README\.md$
        stages: [ commit ]
        language: python
        additional_dependencies:
          - rich==13.6.*
        args: [ ]
        entry: python readme.py
